name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    environment: default
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.GCP_IMAGE_NAME }}
  google:
    environment: default
    runs-on: ubuntu-latest
    steps:
     - 
      name: Google Cloud Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
     -
      name: Connect to VM
      uses: google-github-actions/ssh-compute@v1
      with:
        instance_name: '${{ vars.GCP_INSTANCE_NAME }}'
        zone: 'us-central1-c'
        ssh_private_key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        command: 'docker stop $(docker ps -aq) && docker rm $(docker ps -aq) && docker pull ${{ vars.GCP_IMAGE_NAME }} && docker run -p 5000:5000 --name flask -e POSTGRES_HOST=${{ secrets.NEON_CONNECTION_STRING }} ${{ vars.GCP_IMAGE_NAME }}'
